apiVersion: v1
kind: Service
metadata:
  labels:
    app: shanghaiworldfinancialcenter
  name: shanghaiworldfinancialcenter
  namespace: devices
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 30001
  selector:
    app: shanghaiworldfinancialcenter
  type: LoadBalancer
