apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-jinmaotower
  name: deviceshifu-jinmaotower
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-jinmaotower
  template:
    metadata:
      labels:
        app: deviceshifu-jinmaotower
    spec:
      containers:
        - image: edgehub/deviceshifu-http-http:v0.1.1
          name: deviceshifu-http
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-jinmaotower"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
      volumes:
        - name: deviceshifu-config
          configMap:
            name: configmap-jinmaotower
      serviceAccountName: edgedevice-sa
