apiVersion: v1
kind: Service
metadata:
  labels:
    app: jinmaotower
  name: jinmaotower
  namespace: devices
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 30001
  selector:
    app: jinmaotower
  type: LoadBalancer
