apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-jinmaotower
  name: deviceshifu-jinmaotower
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: deviceshifu-jinmaotower
  type: LoadBalancer
