apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-orientalpearltower
  name: deviceshifu-orientalpearltower
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: deviceshifu-orientalpearltower
  type: LoadBalancer
